// Optional end-to-end QA. Install Playwright separately; the app has no dependencies.
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const url = process.env.APP_URL || 'http://127.0.0.1:4173/kaisereich-run-picker/';
const launch = { headless: true, ...(process.env.BROWSER_CHANNEL ? { channel: process.env.BROWSER_CHANNEL } : {}) };
const profile = await mkdtemp(join(tmpdir(), 'kr-picker-qa-'));
const output = process.env.QA_OUTPUT || 'work/qa';
await mkdir(output, { recursive: true });
const key = 'kaiserreich-run-picker.progress';
const dataset = JSON.parse(await readFile(new URL('../data/paths.json', import.meta.url), 'utf8'));
const optionCount = dataset.countries.reduce((n, c) => n + c.paths.length, 0);
const countryCount = dataset.countries.length;
const completion = `${(100 / optionCount).toFixed(1)}%`;
const errors = [];
let context;
let browser;
let checks = 0;
function check(value, message) { assert.ok(value, message); checks++; console.log(`PASS ${message}`); }
async function saved(page) { return page.evaluate(key => JSON.parse(localStorage.getItem(key))?.progress ?? {}, key); }
async function go(page, view) { await page.locator(`nav a[href="#${view}"]`).click(); await page.locator(`#${view}`).waitFor({ state: 'visible' }); }
async function waitForSpin(page) { await page.waitForFunction(() => !document.getElementById('result-card').hasAttribute('aria-busy')); }
async function upload(page, data) {
  await page.locator('#import-file').setInputFiles({ name: 'save.json', mimeType: 'application/json', buffer: Buffer.from(typeof data === 'string' ? data : JSON.stringify(data)) });
  await page.waitForFunction(() => document.getElementById('import-file').value === '');
}
try {
  context = await chromium.launchPersistentContext(profile, { ...launch, viewport: { width: 1440, height: 1000 } });
  let page = context.pages()[0];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  const responses = [];
  page.on('response', response => responses.push({ url: response.url(), status: response.status() }));
  await page.goto(url);
  await page.locator('#application').waitFor({ state: 'visible' });
  check((await page.locator('#eligible-count').innerText()).includes(`${optionCount} eligible`), 'sample database loads at the project subpath');
  for (const asset of ['/css/style.css', '/js/app.js', '/data/paths.json']) check(responses.some(item => item.url.endsWith(asset) && item.status === 200), `${asset} loads`);
  check(await page.locator('#wheel-entries li').count() === countryCount, 'wheel initially contains one equal slice per country');
  check(await page.locator('#atlas-countries button').count() === countryCount, 'atlas lists every country');
  await page.locator('#country').selectOption('SWE');
  check(await page.locator('#path-choice').isDisabled(), 'path layer waits for ideology selection');
  const swedishReference = await page.locator('#result-flag').getAttribute('src');
  await page.locator('#country-ideology').selectOption('National Populist');
  check(await page.locator('#result-flag').getAttribute('src') !== swedishReference, 'ideology selection changes the nation flag');
  await page.waitForFunction(() => { const image = document.getElementById('result-flag'); return image.complete && image.naturalWidth > 0; });
  await page.locator('#country').selectOption('RUS');
  check(await page.locator('#country-ideology').inputValue() === '' && await page.locator('#path-choice').isDisabled(), 'country change clears dependent selections');
  await page.locator('#country-ideology').selectOption('National Populist');
  const russianReference = await page.locator('#result-flag').getAttribute('src');
  await page.locator('#path-choice').selectOption('RUS_FOCUS_RUS_DECLARE_RUSSIAN_STATE_RUS_DECLARE_RUSSIAN_STATE_0');
  const russianPath = await page.locator('#result-flag').getAttribute('src');
  check(russianPath !== russianReference, 'explicit path cosmetic flag overrides the reference flag');
  check(await page.locator('#atlas-countries [data-map-tag="RUS"] img').getAttribute('src') === russianPath, 'selected map nation uses the path flag');
  await page.locator('#country-ideology').selectOption('Varies by branch');
  check(await page.locator('#result-flag').getAttribute('src') === russianReference, 'ambiguous ideology restores the country reference flag');
  await go(page, 'checklist');
  check(await page.locator('.ideology-group[open]').count() === 0, 'register begins with collapsed ideology groups');
  await page.locator('[data-group-key="ARG:National Populist"] > summary').click();
  check(await page.locator('#status-ARG_CARLES').isVisible(), 'expanding ideology reveals its paths');
  await page.locator('#search').fill('Carles');
  check(await page.locator('#status-ARG_CARLES').isVisible(), 'search automatically reveals matching paths');
  await page.locator('#search').fill('');
  await go(page, 'picker');
  await page.locator('#clear-filters').click();
  await page.locator('#atlas-view').selectOption('Europe');
  check(await page.locator('#campaign-map').getAttribute('viewBox') === '490 35 210 145', 'regional map zoom works');
  await page.locator('#campaign-map [data-map-tag="GER"]').focus();
  await page.keyboard.press('Enter');
  check(await page.locator('#country').inputValue() === 'GER', 'keyboard map selection chooses Germany');
  check(await page.locator('#campaign-map [data-map-tag="GER"]').getAttribute('aria-pressed') === 'true', 'map highlights selected nation');
  await page.locator('#spin-motion').selectOption('off');
  await page.locator('#country-ideology').selectOption({index:1});
  await page.locator('#spin-path').click(); await waitForSpin(page);
  check(await page.locator('#campaign-briefing').isVisible(), 'path result reveals campaign goals');
  check((await page.locator('#campaign-objectives').innerText()).length > 30, 'political objective contains route details');
  check((await page.locator('#campaign-challenge').innerText()).includes('Berlin'), 'challenge belongs to selected country');
  check((await page.locator('#briefing-source').getAttribute('href')).startsWith('https://github.com/Kaiserreich/'), 'objective links to official route source');
  await page.locator('#region').selectOption('East Asia');
  check(await page.locator('#atlas-countries [data-map-tag="GER"]').isDisabled(), 'filtered countries cannot be selected from atlas');
  check(await page.locator('#campaign-briefing').isHidden(), 'stale goals disappear when filters invalidate result');
  await page.locator('#clear-filters').click();
  await page.locator('#atlas-view').selectOption('world');
  await page.locator('#spin-motion').selectOption('on');
  await page.locator('#wheel-spin').focus();
  await page.keyboard.press('Enter');
  check(await page.locator('#spin-both').isDisabled(), 'repeat draws are disabled while the wheel spins');
  const firstRotation = await page.locator('.wheel-rotor').getAttribute('transform');
  await page.waitForTimeout(350);
  const secondRotation = await page.locator('.wheel-rotor').getAttribute('transform');
  check(firstRotation !== secondRotation && await page.locator('#result-card').getAttribute('aria-busy') === 'true', 'wheel visibly rotates over time before revealing a result');
  check(await page.locator('#selection-wheel image').count() === countryCount, 'country wheel displays actual nation flags');
  await waitForSpin(page);
  check(await page.locator('#selection-wheel').getAttribute('data-selected-id') === await page.locator('#result-tag').innerText(), 'keyboard wheel spin lands on the selected country');
  await page.locator('#country').selectOption('GER');
  await page.locator('#wheel-spin').click();
  await waitForSpin(page);
  check((await page.locator('#country-ideology').inputValue()).length > 0, 'wheel selects an ideology before a path');
  await page.locator('#wheel-spin').click(); await waitForSpin(page);
  check((await page.locator('#selection-wheel').getAttribute('data-selected-id')).includes('_'), 'wheel hub continues from ideology into a path draw');
  await page.locator('#spin-country').click();
  await page.locator('#region').selectOption('East Asia');
  await page.waitForTimeout(2300);
  check(!await page.locator('#result-card').getAttribute('aria-busy') && await page.locator('#result-actions').isHidden(), 'changing filters cancels an in-flight spin without revealing its stale result');
  check(await page.locator('#wheel-entries li').count() === dataset.countries.filter(c => c.region === 'East Asia').length, 'country wheel includes all East Asian nations');
  await page.locator('#clear-filters').click();
  await page.locator('#country').selectOption('ARG');
  await page.locator('#route-kind').selectOption('game-rule');
  await page.locator('#country-ideology').selectOption({index:1});
  await page.locator('#spin-path').click();
  await waitForSpin(page);
  check(await page.locator('#result-country').innerText() === 'Argentina', 'country to path maintains the selected country');
  check(await page.locator('#result-flag').evaluate(image => image.complete && image.naturalWidth > 0), 'result nation flag loads');
  check(await page.locator('#result-emblem').evaluate(image => image.complete && image.naturalWidth > 0), 'result ideology emblem loads');
  await page.locator('#start-run').click();
  check(Object.values(await saved(page)).includes('played'), 'Start run saves Played');
  check((await page.locator('#selection-wheel').getAttribute('data-selected-id')).includes('_'), 'saving run status keeps the wheel aligned with the selected path');
  await page.reload();
  await page.locator('#application').waitFor({ state: 'visible' });
  await go(page, 'checklist');
  check(await page.locator('.path-row').count() === optionCount, 'checklist displays every active path');
  check((await page.locator('[data-path-id]').evaluateAll(elements => elements.map(element => element.value))).includes('played'), 'progress survives refresh');
  await page.locator('#search').fill('Carles');
  check(await page.locator('.path-row').count() >= 1, 'accent-insensitive checklist search');
  await page.locator('#status-ARG_CARLES').selectOption('completed');
  check((await saved(page)).ARG_CARLES === 'completed', 'manual checklist changes persist');
  await go(page, 'progress');
  check(await page.locator('#completion-percent').innerText() === completion, 'dashboard computes completion percentage');
  await go(page, 'picker');
  await page.locator('#exclude-completed').check();
  await page.locator('#country').selectOption('ARG');
  await page.locator('#country-ideology').selectOption({index:1});
  await page.locator('#spin-path').click();
  await waitForSpin(page);
  check(await page.locator('#selection-wheel').getAttribute('data-selected-id') !== 'ARG_CARLES', 'completed path is excluded from the draw');
  await page.locator('#status-filter').selectOption('completed');
  check(await page.locator('#result-country').innerText() === 'No paths match.', 'conflicting filters show a useful empty state');
  check(await page.locator('#spin-both').isDisabled(), 'empty pools disable the draw');
  await page.locator('#clear-filters').click();
  await page.locator('input[value="ideology"]').check();
  check(await page.locator('#spin-both').isDisabled(), 'Path to Country requires an ideology');
  await page.locator('#ideology').selectOption('Social Liberal');
  await page.locator('#region').selectOption('South America');
  await page.locator('#spin-both').click();
  await waitForSpin(page);
  check(await page.locator('#result-ideology').textContent() === 'Social Liberal' && await page.locator('#result-region').textContent() === 'South America', 'Path to Country respects the ideology and region');
  await page.locator('input[value="random"]').check();
  await page.locator('#ideology').selectOption('Social Conservative');
  await page.locator('#region').selectOption('North America');
  await page.locator('#spin-both').click();
  await waitForSpin(page);
  check(await page.locator('#result-ideology').textContent() === 'Social Conservative' && await page.locator('#result-region').textContent() === 'North America', 'Fully Random honors combined region and ideology filters');
  await go(page, 'progress');
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#export').click();
  const download = await downloadPromise;
  const exported = JSON.parse(await readFile(await download.path(), 'utf8'));
  check(exported.progress.ARG_CARLES === 'completed' && exported.schemaVersion === 1, 'export produces a valid save download');
  await upload(page, { schemaVersion: 1, progress: { GXC_FEDERALIST_SOCDEM: 'completed', REMOVED_PATH: 'played' } });
  check((await saved(page)).REMOVED_PATH === 'played', 'import preserves unknown IDs');
  check((await saved(page)).ARG_CARLES === 'completed', 'import merges without erasing unrelated progress');
  check((await page.locator('#unknown-count').innerText()).includes('1 saved path'), 'unknown paths are explained');
  const beforeInvalid = await saved(page);
  await upload(page, '{not json');
  check(JSON.stringify(await saved(page)) === JSON.stringify(beforeInvalid), 'malformed import leaves progress unchanged');
  check((await page.locator('#announcement').innerText()).includes('not appear to be a valid'), 'malformed import has a readable error');
  await page.locator('#reset').click();
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  check((await saved(page)).ARG_CARLES === 'completed', 'reset cancellation keeps progress');
  await page.locator('#reset').click();
  await page.locator('#reset-dialog button[value="reset"]').click();
  await page.waitForFunction(key => localStorage.getItem(key) === null, key);
  check(Object.keys(await saved(page)).length === 0, 'confirmed reset erases progress');
  await upload(page, { schemaVersion: 1, progress: { ARG_CARLES: 'completed' } });
  await page.locator('#reset').click();
  await page.keyboard.press('Escape');
  check((await saved(page)).ARG_CARLES === 'completed', 'Escape after a previous confirmed reset never erases data');
  await context.close();
  context = await chromium.launchPersistentContext(profile, { ...launch, viewport: { width: 1440, height: 1000 } });
  page = context.pages()[0];
  await page.goto(url + '#progress');
  await page.locator('#application').waitFor({ state: 'visible' });
  check(await page.locator('#completion-percent').innerText() === completion, 'localStorage survives an actual browser restart');
  await page.reload();
  await page.locator('#application').waitFor({ state: 'visible' });
  check(await page.locator('#progress').isVisible(), 'hash navigation survives refresh under the project subpath');
  await go(page, 'picker');
  await page.locator('#country').selectOption('ARG');
  await page.locator('#country-ideology').selectOption({index:1});
  await page.locator('#spin-path').click();
  await waitForSpin(page);
  await page.screenshot({ path: join(output, 'desktop.png'), fullPage: true, animations: 'disabled' });
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    for (const view of ['picker', 'checklist', 'progress', 'about']) {
      await go(page, view);
      check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${view} has no horizontal overflow at ${width}px`);
    }
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await go(page, 'picker');
  await page.screenshot({ path: join(output, 'mobile.png'), fullPage: true, animations: 'disabled' });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.locator('#spin-motion').selectOption('off');
  const instantStarted = Date.now();
  await page.locator('#spin-both').click();
  await waitForSpin(page);
  check(Date.now() - instantStarted < 1500, 'explicit no-motion control reveals a result immediately');
  check(await page.locator('#result-card').evaluate(element => getComputedStyle(element).animationName) === 'none', 'reduced motion disables reveal animation');
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.evaluate(() => document.documentElement.style.fontSize = '32px');
  check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '200% text size remains within the viewport');
  await context.close(); context = null;

  browser = await chromium.launch(launch);
  const denied = await browser.newContext();
  await denied.addInitScript(() => Object.defineProperty(window, 'localStorage', { get() { throw new DOMException('Access denied', 'SecurityError'); } }));
  const deniedPage = await denied.newPage();
  await deniedPage.goto(url);
  await deniedPage.locator('#application').waitFor({ state: 'visible' });
  await deniedPage.locator('#spin-both').click();
  await waitForSpin(deniedPage);
  await deniedPage.locator('#start-run').click();
  check((await deniedPage.locator('#storage-warning').innerText()).includes('cannot be saved'), 'blocked storage warns and keeps the app usable');
  await denied.close();
  const broken = await browser.newPage();
  await broken.route('**/data/paths.json', route => route.fulfill({ status: 500, body: 'unavailable' }));
  await broken.goto(url);
  await broken.locator('#load-error').waitFor({ state: 'visible' });
  check(await broken.locator('#application').isHidden(), 'data load failure shows recovery instructions');
  await broken.close();
  check(errors.length === 0, `no console or uncaught errors in normal use (${errors.join(', ')})`);
  console.log(`All ${checks} browser checks passed. Screenshots: ${output}. Temporary QA profile: ${profile}`);
} catch (error) {
  const failedPage = context?.pages()[0];
  if (failedPage) await failedPage.screenshot({path:join(output,'failure.png'),fullPage:true}).catch(() => {});
  throw error;
} finally {
  await context?.close();
  await browser?.close();
}
